---
sidebar: sidebar 
permalink: create-workspaces.html 
keywords: manage, workspace, snapshot, project 
summary: NetApp Workload Factory for Builders のワークスペースは、プロジェクト スナップショットに基づいたプロジェクトの Perforce 表現です。ビルダー プロジェクトの一部としてワークスペースを作成できます。 
---
= ビルダーワークスペースの作成
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Builders のワークスペースは、特定の時点におけるプロジェクトの Perforce 表現です。ワークスペースは、プロジェクト スナップショットをベースとして作成されます。  Builders プロジェクト内に新しいワークスペースを作成できます。  Perforce UI からワークスペースを作成できます。

.開始する前に
BuildersとPerforce Helix Visual Clientが統合されていることを確認します。詳細については、を参照してください link:integrate-perforce.html["ビルダーとPerforceの統合"^] 。

.手順
. Perforceにログインします。
. Perforceメニューで、*[表示]*>*[WF]を選択します。
+
Perforce UI 内に Workload Factory ログイン画面が表示されます。

. 次のいずれかを使用してWorkload Factoryにログインします。link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^] 。
. Builders ワークロード タイルで、*プロジェクトの作成* を選択します。
. [ワークスペースの作成]*を選択します。
. [ワークスペースプロジェクトの作成]ページで、次の項目を指定します。
+
.. ワークスペースのベースとして使用するスナップショットを選択します。
.. ワークスペースの名前を入力します。
.. 必要に応じて、ワークスペースを要求するユーザーIDを入力します。この識別子は、このワークスペースを使用する開発者のPerforceユーザーIDと一致する必要があります。


. 「 * Create * 」を選択します。


.結果
ワークスペースが作成され、[ワークスペース]ページのワークスペースのリストに表示されます。
