---
sidebar: sidebar 
permalink: learn-builders.html 
keywords: software builders, development, benefits 
summary: NetApp Workload Factory for Builders は、ソフトウェア ビルダー向けの迅速なビルド環境作成ツールです。 
---
= NetApp Workload Factory for Buildersの詳細
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Builders は、ソフトウェア ビルダー向けの迅速なビルド環境作成ツールです。これにより、個人開発環境の迅速なセットアップが可能になり、時間が節約され、開発者のセルフサービスが可能になるとともに、DevOps チームがインフラストラクチャを制御できるようになります。ビルダーを使用すると、ソフトウェア開発者は特殊なデータ ストレージや開発インフラストラクチャの理解を必要とせずに、ワークスペースをすばやく作成できます。



== NetApp Workload Factory for Builders とは何ですか?

NetApp Workload Factory for Builders は、開発者がさまざまなバージョンのソフトウェアを管理および操作する方法を効率化するように設計されています。Builders は Perforce Helix Core と連携して、ソフトウェア バージョンを即座に複製し、開発、QA、CI/CD 用のワークスペースを作成します。

Builders を使用すると、プロジェクトを簡単に作成し、ソフトウェア環境とその成果物を表すボリュームを割り当てることができます。ソフトウェアを更新するときに、ボリュームのスナップショットを作成して、その時点でのソフトウェアの状態をキャプチャできます。再同期せずに任意のソフトウェア バージョンに即座にアクセスできるため、時間とリソースを節約できます。

NetApp ONTAPのスナップショット機能とクローン機能を使用することで、Builders はソフトウェアのさまざまなバージョンへのアクセスを高速化し、更新をより迅速に開発およびリリースできるようになります。

ワークロードファクトリーの詳細については、link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["ワークロードファクトリーの概要"^] 。



== NetApp Workload Factory for Buildersの機能

NetApp Workload Factory for Builders は、次の機能を提供します。

* プロジェクトの作成、編集、削除
* 定義済みのソフトウェアバージョンのスナップショットを作成する
* ワークスペースの作成と削除（クローンに基づく）
* アクセスポリシーを作成してプロジェクトへのアクセスを制御する
* 各プロジェクトの容量使用状況を分析する
* プロジェクトごとにクローンのサイズ制限とクローンの保持期間を制御する
* Perforceなどのバージョン管理システムと統合




== ビルダーのプロジェクトとワークスペース

ビルダーを使用する場合は、プロジェクトを作成し、ソフトウェア環境とそのアーティファクトを表すボリュームを割り当てます。ソフトウェアの新しいバージョンを作成するたびに、ボリュームデータを再同期し、プロジェクトSnapshotを作成してボリュームの状態を既知のバージョンとしてマークする必要があります。プロジェクトのソースボリュームにローリング更新が適用され、複数のバージョンをマークするためのSnapshotが複数存在する場合があります。各スナップショットは、開発者、QA、またはビルドプロセスが利用できる専用または共有の編集可能なリポジトリであるインスタントクローンとしてすぐに使用できます。特定のソフトウェアバージョンのコンテキスト内のクローンは、ワークスペースです。



== Workload Factory Codebox による自動化

Workload Factoryでは、_Codebox_を使用した自動化が組み込まれています。Codeboxには、次のような自動化の利点があります。

* *コードスニペットの生成*：IAC（Infrastructure as Code）スニペットはリソース作成時に生成されるため、既存のオーケストレーションワークフローとシームレスに統合できます。
* *Infrastructure-as-code のコパイロット*: Codebox は、開発者と DevOps が Workload Factory でサポートされているあらゆる操作を実行するためのコードを生成するのに役立つ Infrastructure-as-code (IaC) コパイロットです。
* *コードビューアと自動化カタログ*:コードボックスは、自動化の迅速な分析のためのコードビューアと、将来の迅速な再利用のための自動化カタログを提供します。




== コスト

Workload Factory の Builders 機能の使用には料金はかかりません。



== ライセンス

Workload Factory の Builders 機能を使用するために、 NetAppからの特別なライセンスは必要ありません。



== 地域

ビルダーは、FSx for ONTAPがサポートされるすべての商用地域でサポートされます。 https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["サポート対象の Amazon リージョンを表示します。"^]

次のAWSリージョンはサポートされません。

* 中国
* GovCloud（US）リージョン
* シークレットクラウド
* トップシークレットクラウド




== サポートを受ける

Amazon FSx for NetApp ONTAPは、AWS ファーストパーティソリューションです。サポートについては、AWS マネジメントコンソールのサポートセンターを使用してケースを開いてください。「FSx for ONTAP」とカテゴリを選択し、必要な情報を入力します。

Workload FactoryまたはWorkload Factoryアプリケーションとサービスに関する一般的な質問については、以下を参照してください。link:get-help-builders.html["Workload Factory のビルダーのヘルプを取得する"] 。
