---
sidebar: sidebar 
permalink: learn-builders.html 
keywords: software builders, development, benefits 
summary: BlueXP  Workload Factory for Buildersは、ソフトウェアビルダー向けの迅速なビルド環境作成ツールです。 
---
= ビルダー向けBlueXP  ワークロードファクトリーの詳細
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  Workload Factory for Buildersは、ソフトウェアビルダー向けの迅速なビルド環境作成ツールです。個人用の開発環境の迅速なセットアップが可能になり、開発者が時間を節約してセルフサービスを利用できるようになると同時に、DevOpsチームがインフラの管理を維持できるようになります。Buildersを使用すると、ソフトウェア開発者は、専用のデータストレージや開発インフラストラクチャの理解を必要とせずに、ワークスペースをすばやく作成できます。



== ビルダーのためのBlueXP  ワークロードファクトリーとは何ですか?

BlueXP  Workload Factory for Buildersは、開発者がソフトウェアのさまざまなバージョンを管理および操作する方法を合理化するように設計されています。ビルダーはPerforce Helix Coreとシームレスに統合して、ソフトウェアバージョンのクローンを瞬時に作成し、開発、QA、CI/CDプロセス用のすぐに使用できるワークスペースを作成します。

Buildersを使用すると、プロジェクトを簡単に作成し、ソフトウェア環境とその成果物を表すボリュームを割り当てることができます。ソフトウェアを更新すると、ボリュームのスナップショットを作成して、その時点のソフトウェアの状態をキャプチャできます。つまり、バージョン管理システムと再同期することなく、ソフトウェアのどのバージョンにも瞬時にアクセスできるため、貴重な時間とリソースを節約できます。

ONTAPのスナップショット機能とクローン機能を活用することで、Buildersは開発ワークフローを強化し、ソフトウェアの複数バージョンへの迅速なアクセスを可能にし、開発サイクルを短縮し、市場投入までの時間を短縮します。

ワークロードファクトリの詳細については、を参照してlink:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["ワークロードファクトリの概要"^]ください。



== ビルダー向けBlueXP  ワークロードファクトリー機能

BlueXP  Workload Factory for Buildersには、次の機能があります。

* プロジェクトの作成、編集、削除
* 定義済みのソフトウェアバージョンのスナップショットを作成する
* ワークスペースの作成と削除（クローンに基づく）
* アクセスポリシーを作成してプロジェクトへのアクセスを制御する
* 各プロジェクトの容量使用状況を分析する
* プロジェクトごとにクローンのサイズ制限とクローンの保持期間を制御する
* Perforceなどのバージョン管理システムと統合




== ビルダーのプロジェクトとワークスペース

ビルダーを使用する場合は、プロジェクトを作成し、ソフトウェア環境とそのアーティファクトを表すボリュームを割り当てます。ソフトウェアの新しいバージョンを作成するたびに、ボリュームデータを再同期し、プロジェクトSnapshotを作成してボリュームの状態を既知のバージョンとしてマークする必要があります。プロジェクトのソースボリュームにローリング更新が適用され、複数のバージョンをマークするためのSnapshotが複数存在する場合があります。各スナップショットは、開発者、QA、またはビルドプロセスが利用できる専用または共有の編集可能なリポジトリであるインスタントクローンとしてすぐに使用できます。特定のソフトウェアバージョンのコンテキスト内のクローンは、ワークスペースです。



== Workload Factoryの動作モード

_basic_、_read_and _automate_という3つの運用モードでは、ワークロード工場の内外に導入するための柔軟なオプションが提供されます。ワークロードファクトリの外部で使用するコードスニペットを使用して、ゼロトラストのIN_BASIC_MODEですぐに価値を得ることができます。_read_and_automate_modesで増分値を取得します。

詳細については、をご覧ください link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["Workload Factoryの動作モード"^]。



== Workload Factory Codeboxによる自動化

Workload Factoryでは、_Codebox_を使用した自動化が組み込まれています。Codeboxには、次のような自動化の利点があります。

* *コードスニペットの生成*：IAC（Infrastructure as Code）スニペットはリソース作成時に生成されるため、既存のオーケストレーションワークフローとシームレスに統合できます。
* *コードとしてのインフラコパイロット*:コードボックスは、開発者とDevOpsがワークロードファクトリでサポートされているすべての操作を実行するためのコードを生成するのを支援するコードとしてのインフラストラクチャ（IAC）コパイロットです。
* *コードビューアと自動化カタログ*:コードボックスは、自動化の迅速な分析のためのコードビューアと、将来の迅速な再利用のための自動化カタログを提供します。




== コスト

ワークロードファクトリのビルダー機能を使用するためのコストはありません。



== ライセンス

ワークロードファクトリのビルダー機能を使用するために、NetAppから特別なライセンスは必要ありません。



=== サポートされている地域

ビルダーは、FSx for ONTAPがサポートされるすべての商用地域でサポートされます。 https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["サポート対象の Amazon リージョンを表示します。"^]

次のAWSリージョンはサポートされません。

* 中国
* GovCloud（US）リージョン
* シークレットクラウド
* トップシークレットクラウド




== サポートを受ける

Amazon FSx for NetApp ONTAP は、AWSファーストパーティの解決策 です。FSx for ONTAPファイルシステム、インフラ、または本サービスを使用する解決策に関する質問やテクニカルサポートの問題については、AWS管理コンソールのサポートセンターを使用してAWSに対するサポートケースをオープンしてください。「 FSX for ONTAP 」サービスと該当するカテゴリを選択します。AWS サポートケースの作成に必要な残りの情報を指定します。

ワークロードファクトリまたはワークロードファクトリのアプリケーションとサービスに関する一般的な質問については、を参照してくださいlink:get-help-builders.html["ワークロード工場のビルダーのサポート"]。
