---
sidebar: sidebar 
permalink: requirements-builders.html 
keywords: Builders, FSx, project, projects 
summary: NetApp Workload Factory for Builders の使用を開始する前に、Workload Factory と AWS が適切にセットアップされていることを確認してください。これには、AWS ログイン認証情報、デプロイされた FSx for ONTAPファイルシステムなどが含まれます。 
---
= ビルダーの要件
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Builders を使用する前に、Workload Factory と AWS が適切にセットアップされていることを確認してください。これには、AWS ログイン認証情報、デプロイされた FSx for ONTAPファイルシステムなどが含まれます。

ワークロードの工場出荷時のログインとアカウント:: 必要となるのは https://docs.netapp.com/us-en/workload-setup-admin/sign-up-saas.html["Workload Factoryでアカウントを設定する"^]次のいずれかを使用してログインします https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]。
AWS のクレデンシャルと権限:: 読み取り/書き込み権限を持つ AWS 認証情報を Workload Factory に追加する必要があります。つまり、Builders では Workload Factory を _読み取り/書き込み_ モードで使用することになります。


現時点では、_基本_モードと_読み取り専用_モードの権限はサポートされていません。

https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Workload FactoryにAWS認証情報を追加する方法を学ぶ"^]

FSx for ONTAPファイルシステム:: 少なくとも1つのFSx for ONTAPファイルシステムが必要です。
+
--
* ファイルシステムは、作成したプロジェクトとワークスペースを保存するためにビルダーによって使用されます。
+
このFSx for ONTAPファイルシステムでは、FlexVolボリュームを使用する必要があります。FlexGroupボリュームはサポートされません。

* AWS FSx for ONTAPファイルシステムが配置されているAWSリージョン、VPC、サブネットを把握しておく必要があります。
* 次の構成のファイルシステムに少なくとも1つのボリュームが必要です。
+
** ボリュームがNFS共有として設定されている必要があります。
** ファイルシステムにリンクが設定されている必要があります。 https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["リンクの詳細"^]です。


* この導入に含まれるAWSリソースに適用するタグのキーと値のペアを検討する必要があります（オプション）。
+
https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["FSx for ONTAPファイルシステムの導入と管理の方法をご確認ください"^]



--

