---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, workload factory, builders, workload factory' 
summary: データベース向けワークロードファクトリーの最新情報をご確認ください。 
---
= ビルダー向けBlueXP  ワークロードファクトリーの最新情報
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload FactoryのBuilders機能の最新情報をご確認ください。



== 2025年6月16日



=== クローンサポート

BlueXP Workload Factory for Builders でプロジェクトのクローンを作成できるようになりました。プロジェクトのクローンを作成すると、Builders はスナップショットから、元のプロジェクトと同じ構成の新しいプロジェクトを作成します。クローン作成は、類似のプロジェクトを素早く作成したり、テスト目的で使用する場合に便利です。新しいプロジェクトのクローンは、Builders の指示に従ってマウントできます。

https://docs.netapp.com/us-en/workload-builders/version-projects.html["ビルダープロジェクトの BlueXP ワークロード ファクトリーのバージョンを管理する"]



== 2025年5月4日



=== 権限に関する用語を更新

ワークロード ファクトリのユーザー インターフェースとドキュメントでは、読み取り権限を示すために「読み取り専用」を使用し、自動化権限を示すために「読み取り/書き込み」を使用するようになりました。



== 2024年12月1日



=== ビルダーワークロードの初回リリース

BlueXP  Workload Factory for Buildersは、ソフトウェアバージョンの消費とアクセスを簡素化し、カスタムツールやスクリプトの必要性を排除します。ソフトウェアバージョンをPerforce Helix Coreと統合されたインスタントクローンとして使用し、開発プロセスに便利なワークスペースとして使用できるため、時間とリソースを節約できます。

初期リリースには、プロジェクトとワークスペースを管理し、Codeboxを使用してアクションを自動化する機能が含まれています。また、BuildersとPerforce Helix Coreを統合することで、プロジェクトごとに異なるバージョンを管理し、すばやく切り替えることができます。
